### ISSUE TITLE
Which browsers are suported?

### ISSUE THREAD

**Issue by solrac901** [mike-goodwin/owasp-threat-dragon#106]
Having issues to create a basic template any recommendation on which browser i can use?

**Comment by mike-goodwin** [comment]
It works on Firefox, Edge and Chrome on Windows, but I recently had problems on Chrome where it was impossible to select or add model elements. That seems to have gone away now. I never had any problems on FF or Edge.

I don't have access to a Mac at the moment, so it is untested on OSX (by me).

**Comment by solrac901** [comment]
Im using Chrome and the elements (process,store,actor,etc) can be added to the diagram i will check in other browsers the version of Chrome that im using its 
Google Chrome is up to date
Version 75.0.3770.142 (Official Build) (32-bit)
Thanks
Quick question exist any other option to export the report or store it ?

**Comment by jgadsden** [comment]
Hello @solrac901 
You can export the threat model as a .pdf report, or print the report. Make sure you have an up to date Threat Dragon, as this was introduced in mid 2019.
Also there is a table of supported browsers at the FAQs tab of [OWASP Threat Dragon](https://owasp.org/www-project-threat-dragon/ ) page
