### ISSUE TITLE
local model storage (for the webapp)

### ISSUE THREAD

**Issue by Trolldemorted** [mike-goodwin/owasp-threat-dragon#126]
Would it be a lot of work to support local storage on the webapp like the electron client does?

This would be great for quick demos for audiences which are unwilling to allow write access to their github repositories, or do not have a github account.

**Comment by jgadsden** [comment]
This would certainly be worthwhile (and probably a lot of work :-) ) because it would also allow Threat Dragon to be deployed as a service, rather than having to locally install the desktop version, in the case where local storage is required

**Comment by jgadsden** [comment]
Migrated to new issue in the OWASP area repo : https://github.com/OWASP/threat-dragon/issues/11
