### ISSUE TITLE
Error when searching for model to import

### ISSUE THREAD

**Issue by jeg1972** [mike-goodwin/owasp-threat-dragon#13]
When I was searching for a model to import, I chose to select a threat model from jeg1972/owasp-threat-dragon/master, unfortunately there wasn't a file to import from that location. but I received the following error message.
![screenshot 2016-05-13 at 20 33 53](https://cloud.githubusercontent.com/assets/842461/15259692/b8b29464-194a-11e6-850b-abc07631e716.png)

**Comment by mike-goodwin** [comment]
Please can you try again. I may have fixed this in the commit I did tonight. This is what I get now when browsing to that repo/branch. Note that this links to e.g. create a new model are broken - this is another issue :)

![image](https://cloud.githubusercontent.com/assets/5851302/15262584/4d0036f2-195b-11e6-88b7-276077183455.png)

**Comment by mike-goodwin-sage** [comment]
Based on our conversation the other day, I'm closing this as fixed. Feel free to re-open if you disagree.

**Comment by mike-goodwin** [comment]
Based on our discussion the other day, I'm closing this issue. Please feel free to re-open if you disagree.
