### ISSUE TITLE
Auto save desktop version

### ISSUE THREAD

**Issue by RobSkye** [mike-goodwin/owasp-threat-dragon#149]
Would be great to have all the changes autosaved everytime you make a modification to a diagram, add a threat..etc.

**Comment by jgadsden** [comment]
Hello @RobSkye , yes, sounds like a good idea. Do you have in mind auto-save to a temporary file so that if TD were to be exited suddenly you would have a backup of the changes? Or is there some other way?

**Comment by RobSkye** [comment]
That could work but maybe it is more simple to just write in the main file every change.

**Comment by jgadsden** [comment]
Migrated to new issue in the OWASP area repo : https://github.com/OWASP/threat-dragon/issues/15
