### ISSUE TITLE
draw.io and/or visio intergration

### ISSUE THREAD

**Issue by gbiagomba** [mike-goodwin/owasp-threat-dragon#150]
Hello,

This is more of a request than an issue. But is there anyways to open a visio file oran xml file from draw.io into this tool? If no, is it possible to  have that added?

**Comment by jgadsden** [comment]
Not able to open visio files or xml files at present, @gbiagomba , but there is possibly a draw.io based version of threat dragon coming along later in the year. This may be able to open these files along with the TD json files, so will keep an eye on this.

**Comment by jgadsden** [comment]
Migrated to new issue in the OWASP area repo : https://github.com/OWASP/threat-dragon/issues/16

**Comment by gbiagomba** [comment]
thank you @jgadsden
