### ISSUE TITLE
Improve the DFD printing

### ISSUE THREAD

**Issue by lukfe85** [mike-goodwin/owasp-threat-dragon#164]
Dear OWASP, 
I am using the latest version 1.3.1 on Mac. If the DFD is too big, the diagram is not correctly printed. The scroll bars appear but the diagram is not complete. Check the screenshot
<img width="881" alt="DFD Print bug" src="https://user-images.githubusercontent.com/80815574/111436919-cb929e00-8702-11eb-9d5d-3461e8bca54a.png">
Thanks

**Comment by jgadsden** [comment]
Hello @lukfe85 - this is a very good point. It is something that we hope to change for version 2.0 later this year. The new area for Threat Dragon is in the OWASP github organisation - do you want to raise the issue there?
https://github.com/OWASP/threat-dragon-core/issues

Cheers, Jon

**Comment by lukfe85** [comment]
Thanks @jgadsden I did it.
