### ISSUE TITLE
Local model storage

### ISSUE THREAD

**Issue by dskrvk** [mike-goodwin/owasp-threat-dragon#22]
Would be great to be able to just create a model from scratch, managed locally, as opposed to something tied to a particular Github repo. This is for evaluation purposes, plus not everyone uses Github for source control.

**Comment by mike-goodwin** [comment]
As it happens, I'm working on a re-architected version that include an online variant will be a cross-platform, local installed variant based on Electron (like the GitHub git client, the Slack client or Visual Studio code). It's quite a major change so it is taking some time though. I'll post back here when is some progress to report.

**Comment by dskrvk** [comment]
OK, glad to hear the project is alive and well. There really is a need for an open-source, easy-to-use threat assessment tool that helps teams follow good security practices.

**Comment by mike-goodwin** [comment]
An update on this:

The desktop variant is basically working, although there is some work to do on it still. If you would like to try it you can find it here:

https://github.com/mike-goodwin/owasp-threat-dragon-desktop

To get it working:

- clone the repo
- install it with `npm install`

Mac: 

- run it with `./node_modules/electron/dist/Electron.app/Contents/MacOS/Electron .`

Windows:

- run it with `./node_modules/electron/dist/electron.exe .`

It works pretty much the same as the online variant, except there is no GitHub sign in and the models are stored as local files. You can still open a demo model, if you want to play with it.

Any feedback or issue reports would be very welcome!

**Comment by dskrvk** [comment]
Awesome, will give it a try!

**Comment by mike-goodwin** [comment]
I'm going to close this since the desktop variant is basically there now.
