### ISSUE TITLE
Bitbucket auth

### ISSUE THREAD

**Issue by dskrvk** [mike-goodwin/owasp-threat-dragon#23]
Bitbucket (which my team happens to use) is a fairly popular alternative to Github. Would be great to have an integration with that as well.

**Comment by javierjeronimo** [comment]
Moreover, Github SSO provides the app write access both to public and private repos of the user, and given that it is still under development, it is dangerous in the event of a bug.

**Comment by mike-goodwin** [comment]
Thank you for your interest in this project! You are the second person to mention that in the last week :)

The [development branch deployment](https://threatdragondev.azurewebsites.net) currently asks for access to public repos only. It's pretty much the same as the master branch at the moment. I'll probably merge from dev to master this weekend.

**Comment by mike-goodwin** [comment]
As an aside - I'm going to make a start on this soon. Sorry for the very long delay, but I was in the middle of  a massive architectural change to the project to enable an installbel desktop variant. I'm getting to the end of that now so I should have time to look at this.

**Comment by mike-goodwin** [comment]
Update: The [master branch deployment](https://threatdragon.org) now only asks for access to public repos. I think you will have to revoke your existing access token and re-authorize to take advantage of this.

**Comment by rkara** [comment]
@mike-goodwin has any progress been made on this?

**Comment by jgadsden** [comment]
Migrated to new issue in the OWASP area repo : https://github.com/OWASP/threat-dragon/issues/1
