### ISSUE TITLE
ERR: Threat Dragon received an invalid request from GitHub

### ISSUE THREAD

**Issue by thatsjet** [mike-goodwin/owasp-threat-dragon#39]
Whenever I try login I get: "Threat Dragon received an invalid request from GitHub. Your internet connection may not be secure!". I'm able to use GitHub as OAuth provider with other sites.

I click login, get directed to GH for auth, succesfully approve use by TD and then get redirected with that error.

**Comment by thatsjet** [comment]
Update: I found a link in the description to threatmodel.org and found I was logged in. Issue might simply be in posting from threatdragon.azuresites.net link won't work.

**Comment by mike-goodwin** [comment]
Hmm. I have seen that sometimes, but never been able to reproduce it reliably. Please can you try a couple of things?

1. What URL are you using? I just moved the demo to https://threatdragon.org. Maybe this has broken something. Or maybe the old URL is broken
2. If you hit refresh on the page with the error, does it fix it?
3. If you clear any cookies for the domain, does that fix it?

Thanks for your interest - hopefully i can get you going.

**Comment by thatsjet** [comment]
Yea, that was it. The link from OWASP goes to the azurewebsites.net link which borks. If you use threatdragon.org it works.

**Comment by mike-goodwin** [comment]
Ah - I forgot to update that. I'll do it now. The problem is that I'm too cheap to pay for the basic tier on Azure websites so I can't use my own SSL cert and domain ;-) I got around it by using CloudFlares crypto for the moment, but the underlying azurewebsites.net URL is still accessible. Sorry abotu that, and thanks for pointing out the problem.

**Comment by mike-goodwin** [comment]
The link from the OWASP wiki is now pointing to https://threatdragon.org
