### ISSUE TITLE
feature request: ability to import/export Microsoft TM7, SVG & PDF

### ISSUE THREAD

**Issue by securestep9** [mike-goodwin/owasp-threat-dragon#50]
ability to import/export Microsoft TM7 format, SVG & PDF will make this tool far more mature and useful.

**Comment by mike-goodwin** [comment]
PR #100 implements the ability to export as PDF. I will wait for feedback on the initial implementation before implementing SVG and Microsoft TM7.

**Comment by jgadsden** [comment]
Migrated to new issue in the OWASP area repo : https://github.com/OWASP/threat-dragon/issues/2
