### ISSUE TITLE
Ability to export diagram with detailed threats into pdf or visio document

### ISSUE THREAD

**Issue by jkrow** [mike-goodwin/owasp-threat-dragon#51]
Excellent tool. Would like the ability to export the diagram, especially from the windows app, as a pdf or visio diagram with full threat detail present and visible.

**Comment by dave-89** [comment]
+1

**Comment by sgiftakis** [comment]
This tool is perfect for organizations that need a basic threat model where security is still maturing. My management is asking to export it but theres no way to do it. Would be awesome if this was possible in some way...maybe not PDF but maybe some nice display format with associated threats etc.

**Comment by mike-goodwin** [comment]
This is implemented in the web version in pull request #100.

The report is pretty basic, so any PRs or comments on ways to improve it are very welcome.
