### ISSUE TITLE
GIT integration to create Issue(s) with Application Repo (Enhancement)

### ISSUE THREAD

**Issue by xolian** [mike-goodwin/owasp-threat-dragon#52]
Ability to create arbitrary GIT Issues in github.com or GHE from the GIT Url of the application/code you are Threat Modeling.

**Comment by jgadsden** [comment]
Hello @xolian - could you give more detail on the enhancement that you are suggesting?

**Comment by jgadsden** [comment]
Migrated to new issue in the OWASP area repo : https://github.com/OWASP/threat-dragon/issues/3
