### ISSUE TITLE
Request to relax test case requirements

### ISSUE THREAD

**Issue by subashsn** [mike-goodwin/owasp-threat-dragon#68]
We've added Gitlab as a provider along with Github for Threat Dragon. Currently it's functional, but the test cases are failing due to ES6 syntax and changes done to accomodate multiple providers; Github and Gitlab. Can we relax this?

If this is okay, I'd be happy to raise a pull request that adds Gitlab integration for Threat Dragon. Thanks

**Comment by Gby56** [comment]
+1 for the Gitlab integration, I've seen your fork and integrating it in Threat Dragon would boost the popularity.
Not sure if Mike is still active for now, but I'm hoping the development goes on

**Comment by mike-goodwin** [comment]
Hello, apologies for the VERY slow reply. If you're still interested in this project I'd like to work with you to merge your GitLab work, preferably in a way that allows both GL and GH (and in future BitBucket).

**Comment by subashsn** [comment]
Sure, let's do this. How do we proceed?

**Comment by jgadsden** [comment]
Hello @subashsn 
Good to see the gitlab integration at https://github.com/appsecco/owasp-threat-dragon-gitlab
Is it possible to combine this back into this original TD repo?
Thanks, Jon

**Comment by jgadsden** [comment]
Migrated to new issue in the OWASP area repo : https://github.com/OWASP/threat-dragon/issues/4
