### ISSUE TITLE
Error: Invalid key length at new Cipheriv (crypto.js:219:16)

### ISSUE THREAD

**Issue by anirbanctts** [mike-goodwin/owasp-threat-dragon#74]
Keep on getting this error after entering github credentials.
Error: Invalid key length     
at new Cipheriv (crypto.js:219:16)
at Object.createCipheriv (crypto.js:619:10)
at encryptData
....

var crypto = require('crypto');
var inputEncoding = 'ascii';
var outputEncoding = 'base64';
var keyEncoding = 'ascii';
var algorithm = 'aes256';

these properties were unchanged. Not sure why this issue keeps on repeating.
using NodeJS 8.11.3 LTS version

**Comment by jgadsden** [comment]
Hello @anirbanctts - are you still getting this error? If not then I can close this issue

**Comment by jgadsden** [comment]
Migrated to new issue in the OWASP area repo : https://github.com/OWASP/threat-dragon/issues/6
